### ISSUE TITLE
GIF comment read incorrectly

### ISSUE THREAD

**Issue by kazarmy** [kohler/gifsicle#43]
The Gifsicle 1.8.7 Windows binaries available from [here](https://eternallybored.org/misc/gifsicle/) (both 32-bit and 64-bit) read incorrectly the comment in the GIF image below. Using the 64-bit binary (`gifsicle -I`), I obtain the following:

```
    comment :name:"Johan Rudolph Thorbecke"\nf:turns=1:map=bctu:show=all:zoom=2\
nplayerno:0:color:(255,   0,   0):name:"Wang Guangmei"\nplayerno:1:color:(255, 2
55,   0):name:"Seni Pramoya"\nplayerno:2:color:(  0, 255, 255):name:"Guyasuta"\n
playerno:3:color:(138,  43, 226)\000\000\000\000\000\000\000\000\000\37777777640
\001\000\37777777641\37777777613\177\000\000P\001=\000\000\000\000\000@a=\000\00
0\000
```

It should be the following (as reported by ImageMagick's `identify -verbose`):

```
    comment: map definition: format=magick|gif:turns=1:map=bctu:show=all:zoom=2
playerno:0:color:(255,   0,   0):name:"Wang Guangmei"
playerno:1:color:(255, 255,   0):name:"Seni Pramoya"
playerno:2:color:(  0, 255, 255):name:"Guyasuta"
playerno:3:color:(138,  43, 226):name:"Johan Rudolph Thorbecke"

```

![comment_bug](https://cloud.githubusercontent.com/assets/12002672/8456279/f4c8fed2-203c-11e5-9c2a-f507849f820e.gif)

**Comment by kohler** [comment]
Thanks for finding this! It's a true bug. I've fixed it and released a new version. However, I don't provide Windows support or distribute binaries. You'll have to compile it yourself or wait for your provider to make a new binary for Windows.

**Comment by kazarmy** [comment]
You forgot to gzip http://www.lcdf.org/gifsicle/gifsicle-1.88.tar.gz i.e. it currently should be renamed to gifsicle-1.88.tar before opening it. Sorry for not realizing this sooner -- I was doing other tasks.

**Comment by kohler** [comment]
This issue is closed. Furthermore your comment is not correct.

**Comment by kazarmy** [comment]
> This issue is closed.

Ok. Last post, hopefully.

> Furthermore your comment is not correct.

The `file` command reports that the downloaded file (gifsicle-1.88.tar.gz) is a POSIX tar archive rather than gzip compressed data. Both GNOME's Archive Manager and 7-Zip on Windows have no problems opening it though, so I guess this is not a big issue (`tar zxvf` doesn't work, but nowadays one should be using `tar xvf`).

**Comment by kohler** [comment]
```
$ wget -q -O-  http://www.lcdf.org/gifsicle/gifsicle-1.88.tar.gz | file -
/dev/stdin: gzip compressed data, from Unix, last modified: Wed Jul  1 11:20:09 2015, max compression
```
